id = "cppx"
name = "CPPX"
description = "Syntax highlighting for C++ JSX-authored UI files (.cppx, .hx)"
version = "0.0.1"
schema_version = 1
authors = ["Henry Ventura"]
repository = "https://github.com/hvent90/cppx-zed"

[grammars.cppx]
repository = "file:///Users/henryventura/.cache/zed-cppx-grammar"
rev = "e768f226c7f590a97dc63530919f85e8585bcaa6"
